# Generated by Django 5.2.7 on 2025-11-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('professor', 'Professor'), ('psicologo', 'Psicólogo'), ('paciente', 'Paciente')], default='psicologo', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
