# Generated by Django 5.2.7 on 2025-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0002_alter_customuser_email_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('professor', 'Professor'), ('psicologo', 'Psicólogo'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
    ]
