# Generated by Django 5.2.7 on 2025-11-11 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0003_alter_customuser_managers_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('crp', models.CharField(max_length=20, unique=True)),
                ('especializacao', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_psicologo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
