# Generated by Django 5.2.7 on 2025-11-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0005_alter_perfilpsicologo_crp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('professor', 'Professor'), ('psicologo', 'Psicologo'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
    ]
