# Generated by Django 5.2.7 on 2025-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0007_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
