# Generated by Django 5.2.7 on 2025-11-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0008_sessao_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psiconnect.perfilpsicologo')),
            ],
        ),
    ]
