# Generated by Django 5.2.7 on 2025-11-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0009_disponibilidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disponibilidade',
            new_name='HorarioDisponivel',
        ),
    ]
