# Generated by Django 5.2.7 on 2025-11-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psiconnect', '0010_rename_disponibilidade_horariodisponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
